"""fix hr access link to non expiring

Revision ID: 2450d7fe3be6
Revises: 3806a6ce008d
Create Date: 2026-01-26 19:18:52.107165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2450d7fe3be6'
down_revision: Union[str, Sequence[str], None] = '3806a6ce008d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_access_links', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('hr_access_links', 'is_used')
    op.drop_column('hr_access_links', 'expires_at')
    op.alter_column('interviews', 'round_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'SCHEDULED'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'SCHEDULED'::character varying"))
    op.alter_column('interviews', 'round_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('hr_access_links', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('hr_access_links', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('hr_access_links', 'is_active')
    # ### end Alembic commands ###
