"""create candidates table

Revision ID: 3bf9c2c26262
Revises: 12f84d85dd79
Create Date: 2026-01-10 10:35:22.728681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf9c2c26262'
down_revision: Union[str, Sequence[str], None] = '12f84d85dd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('highest_qualification', sa.String(length=150), nullable=False),
    sa.Column('experience_type', sa.String(length=20), nullable=False),
    sa.Column('previous_company', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('company_location', sa.String(length=100), nullable=True),
    sa.Column('total_experience_years', sa.Integer(), nullable=True),
    sa.Column('current_ctc', sa.Integer(), nullable=True),
    sa.Column('expected_ctc', sa.Integer(), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('immediate_joining', sa.Boolean(), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_phone'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
