# """create candidates table

# Revision ID: 3db275fabe4e
# Revises: 
# Create Date: 2026-01-09 18:15:13.742982

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision: str = '3db275fabe4e'
# down_revision: Union[str, Sequence[str], None] = None
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
#     # op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
#     op.drop_index(op.f('ix_candidates_phone'), table_name='candidates')
#     op.drop_table('candidates')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('candidates',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
#     sa.Column('position_applied', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('resume_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
#     sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
#     sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
#     sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
#     sa.PrimaryKeyConstraint('id', name=op.f('candidates_pkey'))
#     )
#     op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=True)
#     # op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
#     op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
#     # ### end Alembic commands ###




"""create candidates table

Revision ID: 3db275fabe4e
Revises: 
Create Date: 2026-01-09 18:15:13.742982
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3db275fabe4e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "candidates",
        sa.Column("id", sa.INTEGER(), primary_key=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=15), nullable=False),
        sa.Column("position_applied", sa.String(length=100), nullable=False),
        sa.Column("resume_link", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.create_index(
        op.f("ix_candidates_email"),
        "candidates",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_candidates_phone"),
        "candidates",
        ["phone"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_candidates_phone"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_email"), table_name="candidates")
    op.drop_table("candidates")