"""add resume_url to candidates

Revision ID: 85fd4dcd957a
Revises: 965a298f722b
Create Date: 2026-01-20 16:01:38.011080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85fd4dcd957a'
down_revision: Union[str, Sequence[str], None] = '965a298f722b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'resume_url')
    # ### end Alembic commands ###
